<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Leticia Pablos Robles">
<meta name="dcterms.date" content="2025-08-12">

<title>Assignment #5 - An EEG Processing Pipeline - Answer Key – Fundamentals of Linear Models 2025-2026: Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Workgroup6.html" rel="next">
<link href="./model_multiple2.html" rel="prev">
<link href="./images/Stats_Ling_Cover_1ed.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Workgroup5.html">Workgroup 5: Multiple Regression with R</a></li><li class="breadcrumb-item"><a href="./assignment5_key.html">Assignment #5 - An EEG Processing Pipeline - Answer Key</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fundamentals of Linear Models 2025-2026: Workbook</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workbook organization</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 1: Introduction to R and RStudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro_to_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">✍️ R Syntax</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_libraries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📦 Libraries and Packages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./read_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading and Saving data in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidyverse_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to tidyverse 1: data manipulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_notebooks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducible research using Scripts and Notebooks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment1_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #1 - Answer key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 2: Data Exploration with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_organization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data organization and transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📊Data visualization in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment2_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #2 Data Exploration with R - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 3: Simple Linear Regression with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plot_xy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plotting relationship between two variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Models in R with <em>lm()</em></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment3_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #3 Linear fitting with R - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 4: Simple Linear Regression II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Model output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model assumptions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Model with Categorical predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_reporting1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Model reporting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment4_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #4 - Linear fitting with R II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 5: Multiple Regression with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression with Categorical predictor with more than two levels</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-hoc testing based on Estimated Marginal Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_multiple2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression with several predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment5_key.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Assignment #5 - An EEG Processing Pipeline - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Workgroup 6: Multiple Regression with R II</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#task-1-read-dataframe" id="toc-task-1-read-dataframe" class="nav-link active" data-scroll-target="#task-1-read-dataframe">Task #1: Read dataframe</a></li>
  <li><a href="#task2-summarize-and-reorganize-the-data" id="toc-task2-summarize-and-reorganize-the-data" class="nav-link" data-scroll-target="#task2-summarize-and-reorganize-the-data"><strong>Task#2: Summarize and reorganize the data</strong></a>
  <ul class="collapse">
  <li><a href="#task-2.1-subset-data" id="toc-task-2.1-subset-data" class="nav-link" data-scroll-target="#task-2.1-subset-data">Task #2.1: Subset data</a></li>
  <li><a href="#task-2.2-rearrange-the-data-from-wide-to-long-format" id="toc-task-2.2-rearrange-the-data-from-wide-to-long-format" class="nav-link" data-scroll-target="#task-2.2-rearrange-the-data-from-wide-to-long-format">Task #2.2: Rearrange the data from wide to long format</a></li>
  <li><a href="#task-2.3-calculate-data-averages-in-the-n400-window" id="toc-task-2.3-calculate-data-averages-in-the-n400-window" class="nav-link" data-scroll-target="#task-2.3-calculate-data-averages-in-the-n400-window">Task #2.3: Calculate data averages in the N400 window</a></li>
  </ul></li>
  <li><a href="#task3-create-a-linear-model-of-the-average-voltage" id="toc-task3-create-a-linear-model-of-the-average-voltage" class="nav-link" data-scroll-target="#task3-create-a-linear-model-of-the-average-voltage">Task#3: Create a linear model of the Average Voltage</a>
  <ul class="collapse">
  <li><a href="#task3.1-fz-electrode" id="toc-task3.1-fz-electrode" class="nav-link" data-scroll-target="#task3.1-fz-electrode">Task#3.1: Fz Electrode</a></li>
  <li><a href="#task3.2-cz-electrode" id="toc-task3.2-cz-electrode" class="nav-link" data-scroll-target="#task3.2-cz-electrode">Task#3.2: Cz Electrode</a></li>
  <li><a href="#task-3.3-report-the-models-for-both-fz-and-cz" id="toc-task-3.3-report-the-models-for-both-fz-and-cz" class="nav-link" data-scroll-target="#task-3.3-report-the-models-for-both-fz-and-cz">Task #3.3: Report the models for both Fz and Cz:</a></li>
  <li><a href="#extra-credit-task-4-create-factor-encoding-region-of-interest." id="toc-extra-credit-task-4-create-factor-encoding-region-of-interest." class="nav-link" data-scroll-target="#extra-credit-task-4-create-factor-encoding-region-of-interest.">EXTRA CREDIT: Task #4 Create factor encoding Region of interest.</a></li>
  <li><a href="#task-4.1-create-new-factor" id="toc-task-4.1-create-new-factor" class="nav-link" data-scroll-target="#task-4.1-create-new-factor">Task 4.1: Create new factor</a></li>
  <li><a href="#task-4.2-multiple-linear-regression" id="toc-task-4.2-multiple-linear-regression" class="nav-link" data-scroll-target="#task-4.2-multiple-linear-regression">Task 4.2: Multiple linear regression</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Workgroup5.html">Workgroup 5: Multiple Regression with R</a></li><li class="breadcrumb-item"><a href="./assignment5_key.html">Assignment #5 - An EEG Processing Pipeline - Answer Key</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Assignment #5 - An EEG Processing Pipeline - Answer Key</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 12, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>In this assignment we intended to emulate a full EEG data processing pipeline using the concepts introduced across the different workgroups.</p>
<p>We load the required packages</p>
<section id="task-1-read-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="task-1-read-dataframe">Task #1: Read dataframe</h2>
<p>For the assignment we use a large file containing real EEG data from 17 subjects collected across 4 experimental conditions.</p>
<p>The data is contained in the file <code>/data/eegSampleData.Rda</code> .</p>
<p>Load the data into the environment using <code>readRDS()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>eegData<span class="ot">&lt;-</span><span class="fu">readRDS</span>(<span class="st">'./data/eegSampleData.Rda'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data file contains the following columns:</p>
<ul>
<li><p><strong>time:</strong> numerical time vector in seconds of the collected data with respect to the visual trigger, ranging from -0.2 (200ms before the trigger) to 0.8 (800 ms after the trigger)</p></li>
<li><p><strong>Subject</strong>: Factor with 17 levels from “1” to “17” indicating the participant</p></li>
<li><p><strong>Condition:</strong> categorical factor with 4 levels: “CondA”, “CondB”, “CondC” and “CondD”</p></li>
<li><p><strong>Fp1 to CB2:</strong> 62 columns with voltage values measured at each electrode on the EEG collection.</p></li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the dataset uploaded in the Posit Cloud, Condition was coded as “11”, “22”,“23”,“24” instead of “CondA”, “CondB”, “CondC”, “CondD”.</p>
<p>If you want to replicate this assignment key, run the following line to recode the levels before continuing.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(eegData<span class="sc">$</span>Condition)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CondA"</span>,<span class="st">"CondB"</span>,<span class="st">"CondC"</span>,<span class="st">"CondD"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
<section id="task2-summarize-and-reorganize-the-data" class="level2">
<h2 class="anchored" data-anchor-id="task2-summarize-and-reorganize-the-data"><strong>Task#2: Summarize and reorganize the data</strong></h2>
<p>We want to Evaluate the presence or absence of a N400 Event Related Potential (ERP) on the dataset. The N400 component appears in the range of 250 to 550ms after the stimulus onset, and it is considered a broad central-anterior component.</p>
<p>In order to do that we have to perform the following:</p>
<ul>
<li><p>Calculate the average voltage in the time window 250-550ms for all Electrodes.</p></li>
<li><p>Select the relevant Regions of Interest:</p>
<ul>
<li><p><strong>Anterior:</strong> electrodes F1, F2, F3, F4, F5, F6, Fz</p></li>
<li><p><strong>Central:</strong> electrodes C1, C2, C3, C4, C5, C6, Cz</p></li>
</ul></li>
<li><p>Compare the average voltage across experimental conditions against the <strong>Control Condition</strong>, which in this case is <strong>Condition D</strong></p></li>
</ul>
<section id="task-2.1-subset-data" class="level3">
<h3 class="anchored" data-anchor-id="task-2.1-subset-data">Task #2.1: Subset data</h3>
<p>Select subset of the data for the analysis:</p>
<ul>
<li><p>Time in the range 0.250 to 0.550 s</p></li>
<li><p>Electrodes for the Anterior and Central regions defined above.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>eegDataFiltered <span class="ot">&lt;-</span> eegData <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(time,Subject,Condition,F1,F1,F3,F4,F5,F6,Fz,C1,C2,C3,C4,C5,C6,Cz) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time <span class="sc">&gt;=</span><span class="fl">0.250</span> <span class="sc">&amp;</span> time <span class="sc">&lt;=</span><span class="fl">0.550</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove from the memory the full data set now that we have filtered the data</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(eegData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2.2-rearrange-the-data-from-wide-to-long-format" class="level3">
<h3 class="anchored" data-anchor-id="task-2.2-rearrange-the-data-from-wide-to-long-format">Task #2.2: Rearrange the data from wide to long format</h3>
<p>We convert the data from wide to long format using the steps practiced in Workgroup 2: <a href="https://lpablosrobles.github.io/Fundamentals-Linear-Models-workbook/data_organization.html" class="uri">https://lpablosrobles.github.io/Fundamentals-Linear-Models-workbook/data_organization.html</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>eegDataFiltered_long<span class="ot">&lt;-</span><span class="fu">pivot_longer</span>(eegDataFiltered, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">cols =</span> F1<span class="sc">:</span>Cz, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">names_to =</span> <span class="st">"Electrode"</span>, </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">values_to =</span> <span class="st">"Voltage"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(eegDataFiltered_long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   time Subject Condition Electrode Voltage
  &lt;dbl&gt; &lt;fct&gt;   &lt;fct&gt;     &lt;chr&gt;       &lt;dbl&gt;
1 0.250 1       CondA     F1          -2.93
2 0.250 1       CondA     F3          -2.90
3 0.250 1       CondA     F4          -2.56
4 0.250 1       CondA     F5          -2.33
5 0.250 1       CondA     F6          -2.64
6 0.250 1       CondA     Fz          -2.54</code></pre>
</div>
</div>
</section>
<section id="task-2.3-calculate-data-averages-in-the-n400-window" class="level3">
<h3 class="anchored" data-anchor-id="task-2.3-calculate-data-averages-in-the-n400-window">Task #2.3: Calculate data averages in the N400 window</h3>
<p>Calculate average of data in the N400 window by averaging all points from 250 to 550 ms (already selected before).</p>
<p>We calculate the average in the window for each condition per subject</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>eegDataAveraged <span class="ot">&lt;-</span> eegDataFiltered_long <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Subject,Condition,Electrode) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">AvgVoltage =</span> <span class="fu">mean</span>(Voltage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Subject', 'Condition'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(eegDataAveraged)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
# Groups:   Subject, Condition [1]
  Subject Condition Electrode AvgVoltage
  &lt;fct&gt;   &lt;fct&gt;     &lt;chr&gt;          &lt;dbl&gt;
1 1       CondA     C1            -1.79 
2 1       CondA     C2            -2.50 
3 1       CondA     C3            -1.62 
4 1       CondA     C4            -2.65 
5 1       CondA     C5            -0.884
6 1       CondA     C6            -2.57 </code></pre>
</div>
</div>
</section>
</section>
<section id="task3-create-a-linear-model-of-the-average-voltage" class="level2">
<h2 class="anchored" data-anchor-id="task3-create-a-linear-model-of-the-average-voltage">Task#3: Create a linear model of the Average Voltage</h2>
<section id="task3.1-fz-electrode" class="level3">
<h3 class="anchored" data-anchor-id="task3.1-fz-electrode">Task#3.1: Fz Electrode</h3>
<ul>
<li><p>Select the data in the <strong>Fz electrode</strong></p></li>
<li><p>Create a model to investigate if the AverageVoltage on the Fz electrode in the N400 window is related to the <strong>Condition</strong> factor.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>eegData_Fz <span class="ot">=</span> eegDataAveraged <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Electrode<span class="sc">==</span><span class="st">"Fz"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mFz <span class="ot">&lt;-</span> <span class="fu">lm</span>(AvgVoltage<span class="sc">~</span>Condition, <span class="at">data=</span>eegData_Fz)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mFz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AvgVoltage ~ Condition, data = eegData_Fz)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.7087 -0.7836  0.1005  1.0234  6.0605 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -2.1692     0.5430  -3.995  0.00017 ***
ConditionCondB   1.6390     0.7679   2.135  0.03663 *  
ConditionCondC   2.2767     0.7679   2.965  0.00425 ** 
ConditionCondD   0.8042     0.7679   1.047  0.29887    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.239 on 64 degrees of freedom
Multiple R-squared:  0.1351,    Adjusted R-squared:  0.09455 
F-statistic: 3.332 on 3 and 64 DF,  p-value: 0.02487</code></pre>
</div>
</div>
<p>From the results, we can infer that:</p>
<ul>
<li><p>There appears to be a significant difference across conditions on the Average voltage in a window.</p></li>
<li><p>Condition B and C average voltages differ from the reference Condition A, however Condition D does not.</p></li>
<li><p>The model significance indicates that the inclusion of the Condition predictor in the model improved the explanatory power compared with an intercept only (null) model.</p></li>
</ul>
<p>The exercise Task 3.3, however, asked to consider <strong>Condition D as a reference condition</strong>, while the model by default provides the results considering Condition A as the reference. To correct this, we relevel the Condition factor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>eegData_Fz <span class="ot">&lt;-</span> eegData_Fz <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Condition=</span><span class="fu">relevel</span>(Condition,<span class="st">"CondD"</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>mFz <span class="ot">&lt;-</span> <span class="fu">lm</span>(AvgVoltage<span class="sc">~</span>Condition, <span class="at">data=</span>eegData_Fz)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mFz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AvgVoltage ~ Condition, data = eegData_Fz)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.7087 -0.7836  0.1005  1.0234  6.0605 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)     -1.3650     0.5430  -2.514   0.0145 *
ConditionCondA  -0.8042     0.7679  -1.047   0.2989  
ConditionCondB   0.8348     0.7679   1.087   0.2810  
ConditionCondC   1.4725     0.7679   1.918   0.0596 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.239 on 64 degrees of freedom
Multiple R-squared:  0.1351,    Adjusted R-squared:  0.09455 
F-statistic: 3.332 on 3 and 64 DF,  p-value: 0.02487</code></pre>
</div>
</div>
<p>Now, as you can see, the coefficients changes, and there is only a very marginally significant coefficient (<code>ConditionCondC</code> ), indicating that no Condition is significantly different from the control D.</p>
<section id="marginal-means-calculation" class="level4">
<h4 class="anchored" data-anchor-id="marginal-means-calculation">Marginal means calculation</h4>
<p>Let’s look at the marginal means using the <code>modelbased</code> library and plot them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>emmFz <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(mFz, <span class="at">by=</span><span class="st">"Condition"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>emmFz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Means

Condition |  Mean |   SE |         95% CI | t(64)
-------------------------------------------------
CondD     | -1.36 | 0.54 | [-2.45, -0.28] | -2.51
CondA     | -2.17 | 0.54 | [-3.25, -1.08] | -4.00
CondB     | -0.53 | 0.54 | [-1.61,  0.55] | -0.98
CondC     |  0.11 | 0.54 | [-0.98,  1.19] |  0.20

Variable predicted: AvgVoltage
Predictors modulated: Condition</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emmFz) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we can see from the marginal means and plot, it looks like Condition A and D are slightly different than condition A.</p>
</section>
<section id="post-hoc-analysis" class="level4">
<h4 class="anchored" data-anchor-id="post-hoc-analysis">Post-hoc analysis</h4>
<p>We understand the differences between all values, we run a post-hoc analysis with all pairwise comparisons. Let’s use for example Tukey correction (less strict than Bonferroni)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_contrasts</span>(mFz, <span class="at">contrast=</span><span class="st">"Condition"</span>, <span class="at">p_adjust =</span> <span class="st">"tukey"</span>, <span class="at">backend=</span><span class="st">"emmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Contrasts Analysis

Level1 | Level2 | Difference |         95% CI |   SE | t(64) |     p
--------------------------------------------------------------------
CondA  | CondB  |      -1.64 | [-3.66,  0.39] | 0.77 | -2.13 | 0.153
CondA  | CondC  |      -2.28 | [-4.30, -0.25] | 0.77 | -2.96 | 0.022
CondB  | CondC  |      -0.64 | [-2.66,  1.39] | 0.77 | -0.83 | 0.840
CondD  | CondA  |       0.80 | [-1.22,  2.83] | 0.77 |  1.05 | 0.722
CondD  | CondB  |      -0.83 | [-2.86,  1.19] | 0.77 | -1.09 | 0.699
CondD  | CondC  |      -1.47 | [-3.50,  0.55] | 0.77 | -1.92 | 0.231

Variable predicted: AvgVoltage
Predictors contrasted: Condition
p-value adjustment method: Tukey</code></pre>
</div>
</div>
<p>We see a few interesting things in the output above:</p>
<ul>
<li>Only the contrast between condition C and Condition A seems to be significant, when applying the relevant correction for multiple comparisons. As a comparison, look at what would have been the result if the correction was not applied:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_contrasts</span>(mFz, <span class="at">contrast=</span><span class="st">"Condition"</span>, <span class="at">backend=</span><span class="st">"emmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Contrasts Analysis

Level1 | Level2 | Difference |         95% CI |   SE | t(64) |     p
--------------------------------------------------------------------
CondA  | CondB  |      -1.64 | [-3.17, -0.11] | 0.77 | -2.13 | 0.037
CondA  | CondC  |      -2.28 | [-3.81, -0.74] | 0.77 | -2.96 | 0.004
CondB  | CondC  |      -0.64 | [-2.17,  0.90] | 0.77 | -0.83 | 0.409
CondD  | CondA  |       0.80 | [-0.73,  2.34] | 0.77 |  1.05 | 0.299
CondD  | CondB  |      -0.83 | [-2.37,  0.70] | 0.77 | -1.09 | 0.281
CondD  | CondC  |      -1.47 | [-3.01,  0.06] | 0.77 | -1.92 | 0.060

Variable predicted: AvgVoltage
Predictors contrasted: Condition
p-values are uncorrected.</code></pre>
</div>
</div>
<ul>
<li>In this case also the comparison between Conditions A and B is signficant, but it is likely a Type I error due to the use of multiple comparisons.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Analysis using <code>emmeans</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Considering that the <code>modelbased</code> package is relatively new and the wide usage of <code>emmeans</code> , I include here the same calculation using <code>emmeans</code> for reference, as the nomenclature and output is a bit different. Remember though that <code>modelbased</code> is a wrapper that calls emmeans on the background.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>emmFz_alt <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(mFz,<span class="sc">~</span>Condition)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>emmFz_alt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Condition emmean    SE df lower.CL upper.CL
 CondD     -1.365 0.543 64   -2.450   -0.280
 CondA     -2.169 0.543 64   -3.254   -1.085
 CondB     -0.530 0.543 64   -1.615    0.555
 CondC      0.107 0.543 64   -0.977    1.192

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Using plot directly on the <code>emmeans</code> output produces the same plot in a different format but with the same information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emmFz_alt, <span class="at">horizontal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, to perform pairwise comparisons, the same function <code>emmeans</code> can be used, but using the pairwise word in the formula as below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mFz,pairwise<span class="sc">~</span>Condition)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Condition emmean    SE df lower.CL upper.CL
 CondD     -1.365 0.543 64   -2.450   -0.280
 CondA     -2.169 0.543 64   -3.254   -1.085
 CondB     -0.530 0.543 64   -1.615    0.555
 CondC      0.107 0.543 64   -0.977    1.192

Confidence level used: 0.95 

$contrasts
 contrast      estimate    SE df t.ratio p.value
 CondD - CondA    0.804 0.768 64   1.047  0.7224
 CondD - CondB   -0.835 0.768 64  -1.087  0.6986
 CondD - CondC   -1.472 0.768 64  -1.918  0.2310
 CondA - CondB   -1.639 0.768 64  -2.135  0.1533
 CondA - CondC   -2.277 0.768 64  -2.965  0.0216
 CondB - CondC   -0.638 0.768 64  -0.830  0.8398

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<p>As you can see from the output, the function automatically applied a Tukey correction, without the need to specify it. Results are the same we obtained before</p>
</div>
</div>
</section>
<section id="model-assumption-checking" class="level4">
<h4 class="anchored" data-anchor-id="model-assumption-checking">Model assumption checking</h4>
<p>Finally, let’s check the model assumptions for validity. First on the linearity of the residuals</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(mFz<span class="sc">$</span>residuals)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mFz<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mFz<span class="sc">$</span>residuals, <span class="at">breaks =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mFz<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mFz$residuals
W = 0.93818, p-value = 0.002184</code></pre>
</div>
</div>
<ul>
<li>The qqplot and histogram, show that the values are quite normal, however outliers are affecting the results. In the real data set, with additional subjects this will not appear, and the model will show to be valid. For the purpose of this exercise, we will report the observations.</li>
</ul>
<p>For the homogeneity of variance we use the test that confirms the model meets the assumptions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(mFz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.6019959, Df = 1, p = 0.43782</code></pre>
</div>
</div>
</section>
</section>
<section id="task3.2-cz-electrode" class="level3">
<h3 class="anchored" data-anchor-id="task3.2-cz-electrode">Task#3.2: Cz Electrode</h3>
<p>We repeat the above process for the Cz electrode:</p>
<section id="model-fit" class="level4">
<h4 class="anchored" data-anchor-id="model-fit">Model fit</h4>
<ul>
<li><p>Select the data in the <strong>Cz electrode</strong></p></li>
<li><p>Create a model to investigate if the AverageVoltage on the Fz electrode in the N400 window is related to the <strong>Condition</strong> factor.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>eegData_Cz <span class="ot">=</span> eegDataAveraged <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Electrode<span class="sc">==</span><span class="st">"Cz"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Condition=</span><span class="fu">relevel</span>(Condition,<span class="st">"CondD"</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mCz <span class="ot">&lt;-</span> <span class="fu">lm</span>(AvgVoltage<span class="sc">~</span>Condition, <span class="at">data=</span>eegData_Cz)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mCz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AvgVoltage ~ Condition, data = eegData_Cz)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.3318 -0.9362  0.1938  1.0596  5.1886 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -2.0151     0.5120  -3.936 0.000207 ***
ConditionCondA  -0.2577     0.7241  -0.356 0.723063    
ConditionCondB   1.8329     0.7241   2.531 0.013834 *  
ConditionCondC   2.2794     0.7241   3.148 0.002499 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.111 on 64 degrees of freedom
Multiple R-squared:  0.2263,    Adjusted R-squared:   0.19 
F-statistic: 6.239 on 3 and 64 DF,  p-value: 0.0008772</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mCz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %     97.5 %
(Intercept)    -3.0379764 -0.9921956
ConditionCondA -1.7043200  1.1888510
ConditionCondB  0.3863119  3.2794828
ConditionCondC  0.8327691  3.7259401</code></pre>
</div>
</div>
</section>
<section id="marginal-means-calculation-and-post-hoc-analysis" class="level4">
<h4 class="anchored" data-anchor-id="marginal-means-calculation-and-post-hoc-analysis">Marginal means calculation and post-hoc analysis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>emmCz <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(mCz, <span class="at">by=</span><span class="st">"Condition"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>emmCz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Means

Condition |  Mean |   SE |         95% CI | t(64)
-------------------------------------------------
CondD     | -2.02 | 0.51 | [-3.04, -0.99] | -3.94
CondA     | -2.27 | 0.51 | [-3.30, -1.25] | -4.44
CondB     | -0.18 | 0.51 | [-1.21,  0.84] | -0.36
CondC     |  0.26 | 0.51 | [-0.76,  1.29] |  0.52

Variable predicted: AvgVoltage
Predictors modulated: Condition</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emmCz) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_contrasts</span>(mCz, <span class="at">contrast=</span><span class="st">"Condition"</span>, <span class="at">p_adjust =</span> <span class="st">"tukey"</span>, <span class="at">backend=</span><span class="st">"emmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Contrasts Analysis

Level1 | Level2 | Difference |         95% CI |   SE | t(64) |     p
--------------------------------------------------------------------
CondA  | CondB  |      -2.09 | [-4.00, -0.18] | 0.72 | -2.89 | 0.027
CondA  | CondC  |      -2.54 | [-4.45, -0.63] | 0.72 | -3.50 | 0.005
CondB  | CondC  |      -0.45 | [-2.36,  1.46] | 0.72 | -0.62 | 0.926
CondD  | CondA  |       0.26 | [-1.65,  2.17] | 0.72 |  0.36 | 0.984
CondD  | CondB  |      -1.83 | [-3.74,  0.08] | 0.72 | -2.53 | 0.065
CondD  | CondC  |      -2.28 | [-4.19, -0.37] | 0.72 | -3.15 | 0.013

Variable predicted: AvgVoltage
Predictors contrasted: Condition
p-value adjustment method: Tukey</code></pre>
</div>
</div>
<p>In this case, there are three significant comparisons: between Conditions A and B, A and C and also C and D.</p>
</section>
<section id="model-assumptions-checking" class="level4">
<h4 class="anchored" data-anchor-id="model-assumptions-checking">Model assumptions checking</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(mCz<span class="sc">$</span>residuals)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(mCz<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mCz<span class="sc">$</span>residuals, <span class="at">breaks =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mCz<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mCz$residuals
W = 0.9589, p-value = 0.02476</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(mCz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Non-constant Variance Score Test 
Variance formula: ~ fitted.values 
Chisquare = 0.000360312, Df = 1, p = 0.98486</code></pre>
</div>
</div>
<p>The results are similar to the Fz calculations, were the model failed on the assumption related to the normality of residuals due to a few outliers that would likely disappear when using the data of more subjects.</p>
</section>
</section>
<section id="task-3.3-report-the-models-for-both-fz-and-cz" class="level3">
<h3 class="anchored" data-anchor-id="task-3.3-report-the-models-for-both-fz-and-cz">Task #3.3: Report the models for both Fz and Cz:</h3>
<p>Report the results of the analysis performed in the APA format described in the lecture including if necessary any post-hoc analysis performed if needed to compare against the <u><strong>reference Condition D.</strong></u></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>We saw on the output from the different comparisons that a number of them show significant differences. Which ones to report however <u><strong>depend on your experimental design.</strong></u> The assignment asked to report against a reference condition D, which would imply that the other comparisons not against D are not relevant or interpretable for the experimental manipulation.</p>
<p>This can often be the case in linguistics experiments, where the different conditions are to be compared to a control. Based on this assumption we write the reporting below</p>
</div>
</div>
<blockquote class="blockquote">
<p>In an Event Related Potential (ERP) study, the effect of experimental manipulation &lt;&lt;&lt;HERE THE EXPERIMENT DESCRIPTION&gt;&gt;&gt; was assessed using a linear model analysis to investivate the presence of a N400 component. The analysis was performed on two sites (Electrodes Fz and Cz) on the averaged voltage in the time window [250ms, 450ms]. Three conditions (A, B, C) were compared to a a control condition D.</p>
<p>Linear model results showed a significant effect for Condition both in Electrode Fz (<span class="math inline">\(F(3,64)=3.33,p=.0.25,R^2_{adj}=0.09\)</span>) and Cz (<span class="math inline">\(F(3,64)=6.24,p&lt;.001,R^2{adj}=0.19\)</span>).</p>
<p>In the Frontal region, as measured in the site Fz, the fitted model was:</p>
<p><span class="math display">\[AverageVoltage_{Fz} = -1.36 -0.80\times CondA+0.83\times CondB+1.47\times CondC\]</span></p>
<p>The model did not reveal any significant effect of Condition with respect to the reference Condition D.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>beta</th>
<th>Confidence Interval</th>
<th>t</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (corresponding to Condition D)</td>
<td>-1.36</td>
<td>[-2.45, -0.28]</td>
<td>t(64) = -2.51</td>
<td>p = 0.014</td>
</tr>
<tr class="even">
<td>Condition A</td>
<td>-0.80</td>
<td>[-2.34, 0.73]</td>
<td>t(64) = -1.05</td>
<td>p = 0.299</td>
</tr>
<tr class="odd">
<td>Condition B</td>
<td>0.83</td>
<td>[-0.70, 2.37]</td>
<td>t(64) = 1.09</td>
<td>p = 0.281</td>
</tr>
<tr class="even">
<td>Condition C</td>
<td>1.47</td>
<td>[-0.06, 3.01]</td>
<td>t(64) = 1.92</td>
<td>p = 0.060</td>
</tr>
</tbody>
</table>
<p>In the Central Region, measured at the site Cz, the fitted model was:</p>
<p><span class="math display">\[AverageVoltage_{Cz} = -2.02 -0.26\times CondA+1.83\times CondB+2.28\times CondC\]</span></p>
</blockquote>
<blockquote class="blockquote">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>beta</th>
<th>Confidence Interval</th>
<th>t</th>
<th>p</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (corresponding to Condition D)</td>
<td>-2.02</td>
<td>[-3.04, -0.99]</td>
<td>t(64) = -3.94</td>
<td>p&lt;.001</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Condition A</td>
<td>-0.26</td>
<td>[-1.70, 1.19]</td>
<td>t(64) = -0.36</td>
<td>p = 0.723</td>
<td>p = 0.723</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Condition B</td>
<td>1.83</td>
<td>[0.39, 3.28]</td>
<td>t(64) = 2.53</td>
<td>p = 0.014</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Condition C</td>
<td>2.28</td>
<td>[0.83, 3.73]</td>
<td>t(64) = 3.15</td>
<td>p = 0.002</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Post-hoc testing based on estimation of the marginal means of the model showed a significant positive Average Voltage in Conditions C with respect to Control Condition D (<span class="math inline">\(Diff_{C-D}=2.28, 95\%CI[0.37,4.19],SE=0.72,t(64)3.15,p=0.013\)</span>). The other two conditions showed a marginal significant positive difference in Condition B (<span class="math inline">\(Diff_{B-D}= 1.83, 95\%CI[-0.08,3.74],SE=0.72,t(64)=-2.53,p=0.065\)</span>) and not a significant difference in Condition A (<span class="math inline">\(Diff_{A-D}= -0.26, 95\%CI[-2.17,1.65],SE=0.72,t(64)=0.36,p=0.984\)</span>).</p>
<p>Pairwise post-hoc comparisons were performed using Tukey correction to account for multiple comparisons.</p>
<p>Model assumptions checking revealed deviations from the normality assumptions on both models that would require a more detailed look at the data outliers or likely an increase of the number of subjects in the study.</p>
</blockquote>
</section>
<section id="extra-credit-task-4-create-factor-encoding-region-of-interest." class="level3">
<h3 class="anchored" data-anchor-id="extra-credit-task-4-create-factor-encoding-region-of-interest.">EXTRA CREDIT: Task #4 Create factor encoding Region of interest.</h3>
</section>
<section id="task-4.1-create-new-factor" class="level3">
<h3 class="anchored" data-anchor-id="task-4.1-create-new-factor">Task 4.1: Create new factor</h3>
<p>Create a new variable with a factor to encode the <strong>Region of Interest called ROI</strong> based on the criteria defined above and two levels:</p>
<ul>
<li><p><strong>Anterior:</strong> electrodes F1, F2, F3, F4, F5, F6, Fz</p></li>
<li><p><strong>Central:</strong> electrodes C1, C2, C3, C4, C5, C6, Cz</p></li>
</ul>
<p>Tip: You can create a variable as a function of the value of another variable using <code>case_when()</code> . Read the following page for instructions : <a href="https://www.statology.org/conditional-mutating-r/" class="uri">https://www.statology.org/conditional-mutating-r/</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>eegDataAveraged<span class="ot">&lt;-</span> eegDataAveraged <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Condition=</span><span class="fu">relevel</span>(Condition,<span class="st">"CondD"</span>))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>eegDataAveraged<span class="sc">$</span>roi <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  eegDataAveraged<span class="sc">$</span>Electrode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"F1"</span>,<span class="st">"F2"</span>,<span class="st">"F3"</span>,<span class="st">"F4"</span>,<span class="st">"F5"</span>,<span class="st">"F6"</span>,<span class="st">"Fz"</span>) <span class="sc">~</span> <span class="st">"Anterior"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  eegDataAveraged<span class="sc">$</span>Electrode <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"C1"</span>,<span class="st">"C2"</span>,<span class="st">"C3"</span>,<span class="st">"C4"</span>,<span class="st">"C5"</span>,<span class="st">"C6"</span>,<span class="st">"Cz"</span>) <span class="sc">~</span> <span class="st">"Central"</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>eegDataAveraged<span class="sc">$</span>roi<span class="ot">&lt;-</span><span class="fu">as.factor</span>(eegDataAveraged<span class="sc">$</span>roi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-4.2-multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="task-4.2-multiple-linear-regression">Task 4.2: Multiple linear regression</h3>
<ul>
<li>Create a model to investigate if the AverageVoltage in the N400 window is related to the <strong>Condition</strong> and <strong>ROI</strong> predictors.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mCA <span class="ot">&lt;-</span><span class="fu">lm</span>(AvgVoltage<span class="sc">~</span>Condition<span class="sc">+</span>roi, <span class="at">data =</span> eegDataAveraged)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AvgVoltage ~ Condition + roi, data = eegDataAveraged)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9257 -0.8371  0.0603  1.0342  6.4014 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -1.45219    0.15511  -9.362  &lt; 2e-16 ***
ConditionCondA -0.61770    0.19301  -3.200  0.00142 ** 
ConditionCondB  1.12764    0.19301   5.842 7.24e-09 ***
ConditionCondC  1.55151    0.19301   8.039 2.92e-15 ***
roiCentral      0.03094    0.13688   0.226  0.82124    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.029 on 879 degrees of freedom
Multiple R-squared:  0.1548,    Adjusted R-squared:  0.151 
F-statistic: 40.25 on 4 and 879 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If we calculate the marginal means and plot we can see that there are no major differences between the two ROIs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">estimate_means</span>(mCA,<span class="at">by=</span><span class="fu">c</span>(<span class="st">"Condition"</span>,<span class="st">"roi"</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>emm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Means

Condition | roi      |  Mean |   SE |         95% CI | t(879)
-------------------------------------------------------------
CondD     | Anterior | -1.45 | 0.16 | [-1.76, -1.15] |  -9.36
CondA     | Anterior | -2.07 | 0.16 | [-2.37, -1.77] | -13.34
CondB     | Anterior | -0.32 | 0.16 | [-0.63, -0.02] |  -2.09
CondC     | Anterior |  0.10 | 0.16 | [-0.21,  0.40] |   0.64
CondD     | Central  | -1.42 | 0.15 | [-1.72, -1.13] |  -9.45
CondA     | Central  | -2.04 | 0.15 | [-2.33, -1.74] | -13.56
CondB     | Central  | -0.29 | 0.15 | [-0.59,  0.00] |  -1.95
CondC     | Central  |  0.13 | 0.15 | [-0.16,  0.43] |   0.87

Variable predicted: AvgVoltage
Predictors modulated: Condition, roi</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment5_key_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_contrasts</span>(mCA, <span class="st">"Condition"</span>, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"roi"</span>),<span class="at">p_adjust =</span> <span class="st">"tukey"</span>,<span class="at">backend =</span> <span class="st">"emmeans"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Contrasts Analysis

Level1 | Level2 | roi      | Difference |         95% CI |   SE | t(879) |      p
---------------------------------------------------------------------------------
CondA  | CondB  | Anterior |      -1.75 | [-2.24, -1.25] | 0.19 |  -9.04 | &lt; .001
CondA  | CondC  | Anterior |      -2.17 | [-2.67, -1.67] | 0.19 | -11.24 | &lt; .001
CondB  | CondC  | Anterior |      -0.42 | [-0.92,  0.07] | 0.19 |  -2.20 |  0.125
CondD  | CondA  | Anterior |       0.62 | [ 0.12,  1.11] | 0.19 |   3.20 |  0.008
CondD  | CondB  | Anterior |      -1.13 | [-1.62, -0.63] | 0.19 |  -5.84 | &lt; .001
CondD  | CondC  | Anterior |      -1.55 | [-2.05, -1.05] | 0.19 |  -8.04 | &lt; .001
CondA  | CondB  | Central  |      -1.75 | [-2.24, -1.25] | 0.19 |  -9.04 | &lt; .001
CondA  | CondC  | Central  |      -2.17 | [-2.67, -1.67] | 0.19 | -11.24 | &lt; .001
CondB  | CondC  | Central  |      -0.42 | [-0.92,  0.07] | 0.19 |  -2.20 |  0.125
CondD  | CondA  | Central  |       0.62 | [ 0.12,  1.11] | 0.19 |   3.20 |  0.008
CondD  | CondB  | Central  |      -1.13 | [-1.62, -0.63] | 0.19 |  -5.84 | &lt; .001
CondD  | CondC  | Central  |      -1.55 | [-2.05, -1.05] | 0.19 |  -8.04 | &lt; .001

Variable predicted: AvgVoltage
Predictors contrasted: Condition
p-value adjustment method: Tukey</code></pre>
</div>
</div>
<p>What you can see from the results and the graphs is that the marginal means show difference between conditions, but same behavior is observed across Regions of Interest, without particular differences between Anterior and Central regions.</p>
<p>However, you can see that a number of comparisons that were not significant before are now that we have included more data (more sites). We can compare model with and without a parameter.</p>
<p>Please note that a model with only the Region of Interest <code>roi</code> does not make theoretical sense in general, as it will imply that the activity is different independently of the manipulation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>mCA_0<span class="ot">&lt;-</span><span class="fu">lm</span>(AvgVoltage<span class="sc">~</span>Condition, <span class="at">data=</span>eegDataAveraged)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mCA_0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AvgVoltage ~ Condition, data = eegDataAveraged)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9114 -0.8330  0.0626  1.0369  6.3848 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -1.4355     0.1364 -10.524  &lt; 2e-16 ***
ConditionCondA  -0.6177     0.1929  -3.202  0.00141 ** 
ConditionCondB   1.1276     0.1929   5.846 7.11e-09 ***
ConditionCondC   1.5515     0.1929   8.043 2.82e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.028 on 880 degrees of freedom
Multiple R-squared:  0.1548,    Adjusted R-squared:  0.1519 
F-statistic: 53.71 on 3 and 880 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mCA_0,mCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: AvgVoltage ~ Condition
Model 2: AvgVoltage ~ Condition + roi
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    880 3618.5                           
2    879 3618.3  1   0.21027 0.0511 0.8212</code></pre>
</div>
</div>
<p>As expected, the region of interest does not improve the model.</p>
<p>We will see that introducing an interaction between the two factors can change this interpretation after the Task#5 in Assignment #6.</p>
</section>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./model_multiple2.html" class="pagination-link" aria-label="Multiple Linear Regression with several predictors">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Multiple Linear Regression with several predictors</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Workgroup6.html" class="pagination-link" aria-label="Workgroup 6: Multiple Regression with R II">
        <span class="nav-page-text">Workgroup 6: Multiple Regression with R II</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Fundamentals of Linear Models Workbook was written by Dr.&nbsp;Leticia Pablos Robles</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This workbook was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>