<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Leticia Pablos Robles">
<meta name="dcterms.date" content="2025-08-12">

<title>Multiple Linear Regression: Interactions – Fundamentals of Linear Models 2025-2026: Workbook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./model_contrasts.html" rel="next">
<link href="./Workgroup6.html" rel="prev">
<link href="./images/Stats_Ling_Cover_1ed.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Workgroup6.html">Workgroup 6: Multiple Regression with R II</a></li><li class="breadcrumb-item"><a href="./model_interactions.html">Multiple Linear Regression: Interactions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fundamentals of Linear Models 2025-2026: Workbook</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workbook organization</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 1: Introduction to R and RStudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro_to_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">✍️ R Syntax</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_libraries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📦 Libraries and Packages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./read_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reading and Saving data in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidyverse_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to tidyverse 1: data manipulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_notebooks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reproducible research using Scripts and Notebooks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment1_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #1 - Answer key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 2: Data Exploration with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_organization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data organization and transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📊Data visualization in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment2_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #2 Data Exploration with R - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 3: Simple Linear Regression with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plot_xy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plotting relationship between two variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Models in R with <em>lm()</em></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment3_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #3 Linear fitting with R - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 4: Simple Linear Regression II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_fit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Model output</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model assumptions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Model with Categorical predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_reporting1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple Linear Model reporting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment4_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #4 - Linear fitting with R II - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 5: Multiple Regression with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression with Categorical predictor with more than two levels</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_posthoc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Post-hoc testing based on Estimated Marginal Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_multiple2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple Linear Regression with several predictors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./assignment5_key.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment #5 - An EEG Processing Pipeline - Answer Key</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Workgroup6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Workgroup 6: Multiple Regression with R II</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple Linear Regression: Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Treatment Coding vs.&nbsp;Sum Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_multicollinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multicollinearity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model_spearman.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spearman’s rank correlation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#interaction-with-one-categorical-and-one-continuous-predictor-categoricalcontinuous" id="toc-interaction-with-one-categorical-and-one-continuous-predictor-categoricalcontinuous" class="nav-link active" data-scroll-target="#interaction-with-one-categorical-and-one-continuous-predictor-categoricalcontinuous">Interaction with one categorical and one continuous predictor (Categorical*Continuous)</a>
  <ul class="collapse">
  <li><a href="#centering-continuous-predictors" id="toc-centering-continuous-predictors" class="nav-link" data-scroll-target="#centering-continuous-predictors">Centering continuous predictors</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model selection</a></li>
  </ul></li>
  <li><a href="#interaction-with-two-categorical-predictors-categoricalcategorical" id="toc-interaction-with-two-categorical-predictors-categoricalcategorical" class="nav-link" data-scroll-target="#interaction-with-two-categorical-predictors-categoricalcategorical">Interaction with two categorical predictors (Categorical*Categorical)</a>
  <ul class="collapse">
  <li><a href="#model-reporting" id="toc-model-reporting" class="nav-link" data-scroll-target="#model-reporting">Model reporting</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Workgroup6.html">Workgroup 6: Multiple Regression with R II</a></li><li class="breadcrumb-item"><a href="./model_interactions.html">Multiple Linear Regression: Interactions</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Multiple Linear Regression: Interactions</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 12, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>As described during the last lecture, interactions in a model reflect that the effect of one predictor depends on the level (categorical) or value (continuous) of one or more other predictors.</p>
<p>With two predictors, we discussed a model including and interaction between two predictors <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> would look as follows:</p>
<p><span class="math display">\[
Y=b_0+b_1X_1+b_2X_2+b_3X_1X_2
\]</span></p>
<p>with <span class="math inline">\(b_3\)</span> coefficient indicating the strength of the interaction.</p>
<p>Let’s look at a few examples of two combinations of predictors.</p>
<hr>
<section id="interaction-with-one-categorical-and-one-continuous-predictor-categoricalcontinuous" class="level2">
<h2 class="anchored" data-anchor-id="interaction-with-one-categorical-and-one-continuous-predictor-categoricalcontinuous">Interaction with one categorical and one continuous predictor (Categorical*Continuous)</h2>
<p>To illustrate this, we use the Iconicity model as described in [<span class="citation" data-cites="winter2019statistics">Winter (<a href="references.html#ref-winter2019statistics" role="doc-biblioref">2019</a>)</span> Chapter 8.2, based on the study in <span class="citation" data-cites="winter2017words">(<a href="references.html#ref-winter2017words" role="doc-biblioref">Winter et al. 2017</a>)</span>. Read through the book chapters to see a similar analysis.</p>
<p>Bodo Winter made all data used in the book available in an Open Source Foundation (OSF) directory, from which it can be downloaded directly from R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>iconicity<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'https://osf.io/43btm/download'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Description of the dataset (see full details in Chapter 6 of <span class="citation" data-cites="winter2019statistics">(<a href="references.html#ref-winter2019statistics" role="doc-biblioref">Winter 2019</a>)</span>:</p>
<ul>
<li><p><strong>Iconicity</strong>: degree to which a word form resembles the meaning of a word, based on a rating scale. E.g: onomatopoeic words such as bang and beep are iconic because they imitate the sounds these words describe. This is the measured or outcome variable.</p></li>
<li><p><strong>SER:</strong> Sensory experience rating for a particular word as extracted from a rating study.</p></li>
<li><p><strong>POS (Part of Speech):</strong> Lexical categoryPosition in the sentence where the word was used.</p></li>
</ul>
<p>For the analysis we will look at a subset of Noun and Verb.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>icon<span class="ot">&lt;-</span>iconicity <span class="sc">%&gt;%</span> <span class="fu">filter</span>(POS <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Noun"</span>,<span class="st">"Verb"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we fit a model with both <code>SER</code> and <code>POS</code> as predictors as a reference and look at the effects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggiraphExtra)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>m1<span class="ot">&lt;-</span><span class="fu">lm</span>(Iconicity<span class="sc">~</span>POS<span class="sc">+</span>SER,<span class="at">data=</span>icon)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Iconicity ~ POS + SER, data = icon)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0956 -0.7210 -0.1233  0.6146  3.6902 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.11935    0.10040  -1.189    0.235    
POSVerb      0.60159    0.06388   9.418   &lt;2e-16 ***
SER          0.23319    0.02789   8.362   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.045 on 1476 degrees of freedom
  (782 observations deleted due to missingness)
Multiple R-squared:  0.08226,   Adjusted R-squared:  0.08102 
F-statistic: 66.15 on 2 and 1476 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPredict</span>(m1, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"POS"</span>,<span class="st">"SER"</span>),<span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="model_interactions_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretation of the plot and coefficients are as per last lecture, with same slope (effect of <code>SER</code>) for both levels of <code>POS</code> but with a shift between them.</p>
<p>Let’s look now at what happens if we introduce the interaction in the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m2<span class="ot">&lt;-</span><span class="fu">lm</span>(Iconicity<span class="sc">~</span>POS<span class="sc">*</span>SER,<span class="at">data=</span>icon)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Iconicity ~ POS * SER, data = icon)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8448 -0.7043 -0.1257  0.5864  3.5845 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.27394    0.11065   2.476  0.01341 *  
POSVerb     -0.95542    0.20971  -4.556 5.65e-06 ***
SER          0.11817    0.03108   3.801  0.00015 ***
POSVerb:SER  0.50838    0.06535   7.780 1.36e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.025 on 1475 degrees of freedom
  (782 observations deleted due to missingness)
Multiple R-squared:  0.1184,    Adjusted R-squared:  0.1166 
F-statistic: 66.05 on 3 and 1475 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPredict</span>(m2, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"POS"</span>,<span class="st">"SER"</span>),<span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="model_interactions_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, allowing the model fit to account for an interaction allows a variability of the slope or effect of <code>SER</code> for each of the levels of the other predictor. The <strong>two lines are not parallel</strong> now. The sensory experience has a different impact on Iconicity for Nouns compared to Verbs.</p>
<p>Ignoring a data interaction when present in the data leads to incorrect interpretation of the fit results.</p>
<p>The fitted model is:</p>
<p><span class="math display">\[ Iconicity=0.274-0.955\times POS_{Verb}+0.118\times SER+0.508\times POS_{Verb}\times SER\]</span></p>
<p>Let’s check what every coefficient means:</p>
<ul>
<li><p><span class="math inline">\(b_0\)</span> - intercept: corresponds to the Iconicity for a <strong><em>Noun</em></strong> (POS=0) for a word with Sensory Experience Rating = 0. Note that this is not directly interpretable, since SER=0 is not even possible for this rating.</p></li>
<li><p><span class="math inline">\(b_1\)</span> - slope coefficient for <em>POS</em>. Represents the effect in the Noun-Verb difference <strong><em>for words</em></strong> <strong><em>with SER=0</em></strong>. If you were to extend the plot above to the left to SER = 0, you can see that the lines for Verb would be below the line for Noun.</p></li>
<li><p><span class="math inline">\(b_2\)</span> - slope coefficient for <em>SER</em>. Represents the slope of the SER <strong>only in the case that POS=0 (Noun)</strong>. So 0.118 is the slope of the red curve</p></li>
<li><p><span class="math inline">\(b_3\)</span> - indicates the change in the slope of <em>SER</em> when <strong>POS=1 (Verb)</strong>, so the slope of the green curve is <span class="math inline">\(b_2+b_3=0.118+0.508=0.626\)</span>.</p></li>
</ul>
<section id="centering-continuous-predictors" class="level3">
<h3 class="anchored" data-anchor-id="centering-continuous-predictors">Centering continuous predictors</h3>
<hr>
<p>A simpler way to interpret intercepts when involving continuous predictors can be done if the predictors are <strong>centered.</strong></p>
<p>Centering predictors involves substracting the mean from all the values. It does not affect the model fit quality, but the coefficients become directly interpretable. Let’s create a new variable centering <code>SER</code> called <code>SER_c</code> and fit a new model with the centered variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>icon<span class="ot">&lt;-</span>icon <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SER_c=</span>SER<span class="sc">-</span><span class="fu">mean</span>(SER, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>m2_c<span class="ot">&lt;-</span><span class="fu">lm</span>(Iconicity<span class="sc">~</span>POS<span class="sc">*</span>SER_c, <span class="at">data=</span>icon)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Iconicity ~ POS * SER_c, data = icon)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8448 -0.7043 -0.1257  0.5864  3.5845 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    0.66423    0.03102  21.414  &lt; 2e-16 ***
POSVerb        0.72371    0.06456  11.209  &lt; 2e-16 ***
SER_c          0.11817    0.03108   3.801  0.00015 ***
POSVerb:SER_c  0.50838    0.06535   7.780 1.36e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.025 on 1475 degrees of freedom
  (782 observations deleted due to missingness)
Multiple R-squared:  0.1184,    Adjusted R-squared:  0.1166 
F-statistic: 66.05 on 3 and 1475 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggPredict</span>(m2_c, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"POS"</span>,<span class="st">"SER"</span>),<span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="model_interactions_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The fitted model is:</p>
<p><span class="math display">\[ Iconicity=0.664+0.724\times POS_{Verb}+0.118\times SER_c+0.508\times POS_{Verb}\times SER_c\]</span></p>
<p>Let’s check what every coefficient means:</p>
<ul>
<li><p><span class="math inline">\(b_0\)</span> - intercept: corresponds to the Iconicity for a <strong><em>Noun</em></strong> (POS=0) for a word with <strong>average SER</strong> (SER_c=0). This has not a direct interpretation.</p></li>
<li><p><span class="math inline">\(b_1\)</span> - slope coefficient for <em>POS</em>. Represents the effect in the Noun-Verb difference <strong><em>for words</em></strong> <strong><em>with average SER</em></strong>.</p></li>
<li><p><span class="math inline">\(b_2\)</span> - slope coefficient for <em>SER</em>. Represents the slope of the SER <strong>only in the case that POS=0 (Noun)</strong>. Same as before.</p></li>
<li><p><span class="math inline">\(b_3\)</span> - indicates the change in the slope of <em>SER</em> when <strong>POS=1 (Verb)</strong>. Same as before.</p></li>
</ul>
</section>
<section id="model-selection" class="level3">
<h3 class="anchored" data-anchor-id="model-selection">Model selection</h3>
<hr>
<p>The model coefficients show significant <strong>simple effects</strong> and <strong>interactions</strong>, and it shows to improve the variance explained compared with a model without interactions.</p>
<p>To compare them we can also perform a model comparison as shown in previous workgroups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model without interaction with centered variable</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>m1_c<span class="ot">&lt;-</span><span class="fu">lm</span>(Iconicity<span class="sc">~</span>POS<span class="sc">+</span>SER_c,<span class="at">data=</span>icon)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_c,m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Iconicity ~ POS + SER_c
Model 2: Iconicity ~ POS * SER_c
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1476 1611.9                                  
2   1475 1548.3  1    63.533 60.523 1.358e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m1_c,m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     df      AIC
m1_c  4 4332.468
m2_c  5 4274.993</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(m1_c,m2_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     df      BIC
m1_c  4 4353.664
m2_c  5 4301.488</code></pre>
</div>
</div>
<p>All three test identify a significant improvement of the model fit including the interaction.</p>
</section>
</section>
<section id="interaction-with-two-categorical-predictors-categoricalcategorical" class="level2">
<h2 class="anchored" data-anchor-id="interaction-with-two-categorical-predictors-categoricalcategorical">Interaction with two categorical predictors (Categorical*Categorical)</h2>
<hr>
<p>For this example, we will use again the subset of the real data from a Self-Paced Reading study on Negative Polarity Items and complementizer agreement in Basque <span class="citation" data-cites="pablos2009negative">(<a href="references.html#ref-pablos2009negative" role="doc-biblioref">Pablos and Saddy 2009</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">'./data/BasqueNPISampleEx5.Rda'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>basquenpi_Ex5</code> data frame contains only the data from Region Number 8 (complementizer position), which was considered the “critical region” for analysis in the experiment.</p>
<p>From the dataframe, we will select a subset of the data columns for the analysis and introduce a transformation to inverse Reading Time (1/RWRT) to normalize the data as discussed in the assignment</p>
<ul>
<li><strong>Subject</strong> – Factor identifying the participant on the experiment (coded as a number from 1 to 32)</li>
<li><strong>EmbeddedSubject</strong> – Factor/predictor indicating the nature of the embedded subject with the following levels:
<ul>
<li>NP – for target sentences with a Noun Phrase as subject</li>
<li>NPI – for target sentences with a Negative Polarity Item as subject</li>
</ul></li>
<li><strong>Agreement Morphology</strong> – Factor/predictor indicating the nature of agreement with the following levels:
<ul>
<li>Declarative – for target sentences that contained a complementizer with declarative morphology</li>
<li>Partitive – for target sentences that contained a complementizer with partitive morphology</li>
</ul></li>
<li><strong>RWRT</strong> – Raw (recorded) Reading Time of the word [milliseconds]</li>
<li><strong>InvRWRT</strong> - Inverse Raw Reading Time [in seconds]</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dataBasque<span class="ot">&lt;-</span>basquenpi_Ex5 <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Item, Subject, EmbeddedSubject, AgreementMorphology, RWRT) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">InvRWRT=</span><span class="dv">1</span><span class="sc">/</span>(RWRT<span class="sc">/</span><span class="dv">1000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again, let’s fit a model with interaction and a model without and compare them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelbased)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>mbasque_1<span class="ot">&lt;-</span><span class="fu">lm</span>(InvRWRT<span class="sc">~</span>EmbeddedSubject<span class="sc">+</span>AgreementMorphology, <span class="at">data=</span>dataBasque)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mbasque_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = InvRWRT ~ EmbeddedSubject + AgreementMorphology, 
    data = dataBasque)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.72727 -0.42095  0.01369  0.38429  2.70877 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    2.1050     0.0394  53.422  &lt; 2e-16 ***
EmbeddedSubjectNPI            -0.1757     0.0455  -3.862 0.000122 ***
AgreementMorphologyPartitive  -0.1537     0.0455  -3.378 0.000766 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6304 on 765 degrees of freedom
Multiple R-squared:  0.03327,   Adjusted R-squared:  0.03074 
F-statistic: 13.16 on 2 and 765 DF,  p-value: 2.394e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>emm_basque_1<span class="ot">&lt;-</span><span class="fu">estimate_means</span>(mbasque_1, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"EmbeddedSubject"</span>,<span class="st">"AgreementMorphology"</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>emm_basque_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Means

EmbeddedSubject | AgreementMorphology | Mean |   SE |       95% CI | t(765)
---------------------------------------------------------------------------
NP              | Declarative         | 2.10 | 0.04 | [2.03, 2.18] |  53.42
NPI             | Declarative         | 1.93 | 0.04 | [1.85, 2.01] |  48.96
NP              | Partitive           | 1.95 | 0.04 | [1.87, 2.03] |  49.52
NPI             | Partitive           | 1.78 | 0.04 | [1.70, 1.85] |  45.06

Variable predicted: InvRWRT
Predictors modulated: EmbeddedSubject, AgreementMorphology</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emm_basque_1) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="model_interactions_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And now with the interaction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mbasque_2<span class="ot">&lt;-</span><span class="fu">lm</span>(InvRWRT<span class="sc">~</span>EmbeddedSubject<span class="sc">*</span>AgreementMorphology, <span class="at">data=</span>dataBasque)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mbasque_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = InvRWRT ~ EmbeddedSubject * AgreementMorphology, 
    data = dataBasque)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.69400 -0.44454  0.03515  0.39684  2.67551 

Coefficients:
                                                Estimate Std. Error t value
(Intercept)                                      2.13822    0.04546  47.031
EmbeddedSubjectNPI                              -0.24224    0.06430  -3.768
AgreementMorphologyPartitive                    -0.22025    0.06430  -3.426
EmbeddedSubjectNPI:AgreementMorphologyPartitive  0.13307    0.09093   1.463
                                                Pr(&gt;|t|)    
(Intercept)                                      &lt; 2e-16 ***
EmbeddedSubjectNPI                              0.000177 ***
AgreementMorphologyPartitive                    0.000646 ***
EmbeddedSubjectNPI:AgreementMorphologyPartitive 0.143754    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.63 on 764 degrees of freedom
Multiple R-squared:  0.03597,   Adjusted R-squared:  0.03219 
F-statistic: 9.503 on 3 and 764 DF,  p-value: 3.618e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mbasque_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                      2.5 %      97.5 %
(Intercept)                                      2.04897153  2.22747080
EmbeddedSubjectNPI                              -0.36846214 -0.11602605
AgreementMorphologyPartitive                    -0.34646508 -0.09402899
EmbeddedSubjectNPI:AgreementMorphologyPartitive -0.04542944  0.31156911</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>emm_basque_2<span class="ot">&lt;-</span><span class="fu">estimate_means</span>(mbasque_2, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"EmbeddedSubject"</span>,<span class="st">"AgreementMorphology"</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>emm_basque_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Means

EmbeddedSubject | AgreementMorphology | Mean |   SE |       95% CI | t(764)
---------------------------------------------------------------------------
NP              | Declarative         | 2.14 | 0.05 | [2.05, 2.23] |  47.03
NPI             | Declarative         | 1.90 | 0.05 | [1.81, 1.99] |  41.70
NP              | Partitive           | 1.92 | 0.05 | [1.83, 2.01] |  42.19
NPI             | Partitive           | 1.81 | 0.05 | [1.72, 1.90] |  39.79

Variable predicted: InvRWRT
Predictors modulated: EmbeddedSubject, AgreementMorphology</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(emm_basque_2) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="model_interactions_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, the “slopes” of the effect and coefficient values have change, and so is the interpretation.</p>
<p>The fitted model is:</p>
<p><span class="math display">\[ (1/RWRT)=2.138-2.422\times EmbeddedSubject_{NPI}-2.220\times AgreementMorphology_{Partitive}+0.133\times EmbeddedSubject_{NPI}\times AgreementMorphology_{Partitive}\]</span></p>
<p>Let’s check what every coefficient means:</p>
<ul>
<li><p><span class="math inline">\(b_0\)</span> - intercept: corresponds to the Inverse Raw Reading Time for the reference cell in the design: <strong><em>EmbeddedSubject = NP</em></strong> (<code>EmbeddedSubjectNPI=0</code>) and <strong><em>AgreementMorphology = Declarative</em></strong> (<code>AgreementMorphologyPartitive=0</code>).</p></li>
<li><p><span class="math inline">\(b_1\)</span> - slope coefficient for <em>EmbeddedSubject</em>. Represents the effect in the InvRWRT <strong><em>for EmbeddedSubject=NPI</em></strong> <u>compared with the reference</u> cell (NP, Declarative), while <strong><em>AgreementMorphology = Declarative</em></strong></p></li>
<li><p><span class="math inline">\(b_2\)</span> - slope coefficient for <em>AgreementMorphology</em>. Represents the change in InvRWRT <strong><em>for AgreementMorphology = Partitive</em></strong> <u>compared with the reference</u> cell (NP, Declarative), while <strong><em>EmbeddedSubject = NP</em></strong></p></li>
<li><p><span class="math inline">\(b_3\)</span> - indicates the change with respect to other coefficients when <strong><em>EmbeddedSubject=NPI and AgreementMorphology = Partitive</em></strong></p></li>
</ul>
<p>So the estimated values are the following:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Agreement Morphology = Declarative</strong></td>
<td><strong>Agreement Morphology = Partitive</strong></td>
</tr>
<tr class="even">
<td><strong>Embedded Subject = NP</strong></td>
<td><span class="math inline">\(b_0\)</span></td>
<td><span class="math inline">\(b_0+b_2\)</span></td>
</tr>
<tr class="odd">
<td><strong>Embedded Subject = NPI</strong></td>
<td><span class="math inline">\(b_0+b_1\)</span></td>
<td><span class="math inline">\(b_0+b_1+b_2+b_3\)</span></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Simple effects vs Main effects</strong></p>
<p>The effects defined by <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> are called <strong>simple effects</strong> as they represent the impact of a particular variable <u>for a specific level of the other predictor.</u></p>
<p>In general, in research what is of interest is the effect of a predictor <u>on the average response</u> independently of the other predictors, which is referred to as <strong>main effects.</strong></p>
<p>We look at how to evaluate main effects in the next section on Contrast Coding.</p>
</div>
</div>
<section id="model-reporting" class="level3">
<h3 class="anchored" data-anchor-id="model-reporting">Model reporting</h3>
<hr>
<p>Finally, to wrap-up we describe what should be included when reporting a model with interactions:</p>
<ul>
<li><p><strong>Report Overall Model:</strong> State the model’s significance and fit (<span class="math inline">\(F, df, p, R^2,R^2_{adj}\)</span>)</p></li>
<li><p><strong>Provide Table of Coefficients:</strong> Use a table for detailed results.</p>
<ul>
<li><p><strong>Columns:</strong> Unstandardized Coefficients (<em>b</em>), Standard Error (<em>SE</em>), <em>t</em>, <em>p</em>, 95% Confidence Interval (<em>CI</em>).</p></li>
<li><p><strong>Rows:</strong> Intercept, predictors, and the Interaction Terms</p></li>
<li><p><strong>Italics:</strong> Italicize statistical symbols like <em>b</em>, <em>SE</em>, <em>t</em>, <em>p</em>, <em>M</em>, <em>SD</em>, <em>R²</em>.</p></li>
</ul></li>
<li><p><strong>Significant Interaction:</strong> If the interaction <em>p</em>-value is significant (e.g., &lt; .05), explain that the effect.</p>
<ul>
<li>Report the unstandardized coefficients for the interaction (<em>B</em><sub>interaction</sub>) and the main effect it modifies (<em>B</em><sub>IV1</sub>).</li>
</ul></li>
<li><p><strong>Explain effects:</strong></p>
<ul>
<li><p>When including a continuous predictor and a categorical predictor as moderator describe and plot the slopes at meaningful predicted values to illustrate the interaction</p></li>
<li><p>With categorical predictors report the Estimated Marginal Means at the specific categories of the predictors.</p></li>
</ul></li>
<li><p>If using data transformation, report coefficients directly from the model in transformed units, but Marginal Means in back-transformed units.</p></li>
</ul>
<p>Example:</p>
<blockquote class="blockquote">
<p>Multiple linear regression was performed to assess the relationship between the <em>Reading Time</em> measured in milliseconds and the nature of the <em>Embedded Subject</em> (NPI or NP) and the <em>Morphological Agreement</em> (Declarative or Partitive).</p>
<p>Raw Reading Time (RWRT) data was transformed using an inverse transformation to address deviations from linear model assumptions observed after fit of RWRT. The model’s intercept</p>
<p>The model (formula: 1/RWRT ~ EmbeddedSubject * AgreementMorphology), explains a statistically significant although weak proportion of the data variance (<span class="math inline">\(F(3,764)=9.50,p&lt;.001,R^2=0.03\)</span>). The model was fit using treatment coding, with the model’s intercept corresponding to the reference condition <em>EmbeddedSubject = NP</em> and <em>AgreementMorphology = Declarative</em>.</p>
<p>The table below summarizes the coefficients of the model:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>term</th>
<th>b*</th>
<th>SE</th>
<th>t</th>
<th>p</th>
<th>95%CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>2.14</td>
<td>0.045</td>
<td>47.0</td>
<td>&lt;.001</td>
<td>[2.05, 2.23]</td>
</tr>
<tr class="even">
<td>EmbeddedSubject_NPI</td>
<td>-0.24</td>
<td>0.064</td>
<td>-3.77</td>
<td>&lt;.001</td>
<td>[-0.37, -0.12]</td>
</tr>
<tr class="odd">
<td>AgreementMorphology_Partitive</td>
<td>-0.22</td>
<td>0.064</td>
<td>-3.43</td>
<td>&lt;.001</td>
<td>[-0.35, -0.09]</td>
</tr>
<tr class="even">
<td>EmbeddedSubject_NPI:AgreementMorphology_Partitive</td>
<td>0.13</td>
<td>0.09</td>
<td>1.45</td>
<td>0.144</td>
<td>[-0.05, 0.31]</td>
</tr>
</tbody>
</table>
</blockquote>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-pablos2009negative" class="csl-entry" role="listitem">
Pablos, Leticia, and Douglas Saddy. 2009. <span>“Negative Polarity Items and Complementizer Agreement in Basque.”</span> <em>Brain Talk</em>, 61.
</div>
<div id="ref-winter2019statistics" class="csl-entry" role="listitem">
Winter, Bodo. 2019. <em>Statistics for Linguists: An Introduction Using r</em>. Routledge.
</div>
<div id="ref-winter2017words" class="csl-entry" role="listitem">
Winter, Bodo, Marcus Perlman, Lynn K Perry, and Gary Lupyan. 2017. <span>“Which Words Are Most Iconic? Iconicity in English Sensory Words.”</span> <em>Interaction Studies</em> 18 (3): 443–64.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Workgroup6.html" class="pagination-link" aria-label="Workgroup 6: Multiple Regression with R II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Workgroup 6: Multiple Regression with R II</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./model_contrasts.html" class="pagination-link" aria-label="Treatment Coding vs. Sum Coding">
        <span class="nav-page-text">Treatment Coding vs.&nbsp;Sum Coding</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Fundamentals of Linear Models Workbook was written by Dr.&nbsp;Leticia Pablos Robles</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This workbook was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>