---
editor: visual
---

# Reading and Saving data in R

## Reading data from files {#sec-r-read}

In most of the cases, the

We cover below examples for **importing data in R**, covering the most common methods and packages.

### Data from text files

The most generic function to read data from a text file is `read.table()` . The arguments allow to define if the data includes a header (i.e. a first row with the names of the columns/variables) and the separator used

Note that by default the argument is `header = FALSE` so you should explicitly change it to `TRUE` in case you have a first line in your file with the columns names.

For example, if we want to load a file called `file.txt` , TAB separated, we will use the function below.

``` r
data <- read.table("file.txt", header = TRUE, sep = "\t")
```

### Data from CSV files

Many experimental data is saved in a text or CSV (Comma separated) file. The best method to read data from these files is to use the `readr` package that is loaded as part of the `tidyverse` .

``` r
library(readr)
data <- read_csv("yourfile.csv")  # Load a CSV file  
```

If your data is tab-separated, you can use the function `read_tsv()` . By default, the functions expect that the first row contains the names of the columns/variables to be read. If that is not the case, you should modify the argument `col_names = FALSE` .

### Data from Excel files

The best way to read Excel files is using the `readxl` package. If your file has several worksheets, you can use the `sheet` argument to specify either an index or the name of the worksheet to read.

``` r
# If not yet available, install the package
install.packages("readxl")

# load library
library(readxl)

# Using readxl
data <- read_excel("file.xlsx", sheet = 1)
```

### Data in R files

Data can also be saved and loaded in *R format* directly

### Data from SPSS

The `haven` package can be used to read directly `.sav` files from SPSS.

``` r
# If not yet available, install the package
install.packages("haven")

# Load library
library(haven)

# Read the SPSS .sav file
data <- read_sav("file.sav")
```

# Saving data

## Save to R format

## Save to text

# 
