---
title: "Libraries and Packages"
author: "Dr. Leticia Pablos Robles"
format: html
editor: visual
---

## 

# 📦 Libraries and Packages

One of the big benefits of *R* in comparison with other statistics packages is its open nature. The functionality is easily extended by groups all around the world by developing libraries that can be easily installed and used.

R packages extend the functionality of R by providing additional functions, data, and documentation. They are written by a worldwide community of R users and can be downloaded for free from the internet.

For example, in several exercises in this book we use a library (created by Baayen) that contains some utilities and a few sample datasets with linguistics examples.

The library should be loaded to be used using the *library()* function.

``` r
library(languageR)
```

## Install and Use a Package

Packages have to be **installed** [and]{.underline} **loaded** before using them.

We install packages only once

``` r
install.packages("dplyr") 
library(dplyr) mtcars %>% filter(cyl == 6) %>% summarise(avg_mpg = mean(mpg)) 
```

## 

## Using RStudio help
